#!/bin/sh

calendar() {
  LOCK_FILE="$HOME/.cache/eww-calendar.lock"
  EWW_BIN="/usr/bin/eww"

  run() {
    ${EWW_BIN} -c $HOME/.config/eww open calendar
  }

  # run eww daemon if not running
  if [[ ! 'pidof eww' ]]; then
    ${EWW_BIN} daemon
    sleep 1
  fi

  # open widgets
  if [[ ! -f "$LOCK_FILE" ]]; then
    touch "$LOCK_FILE"
    run
  else
    ${EWW_BIN} -c $HOME/.config/eww close calendar
    rm "$LOCK_FILE"
  fi
}

if [ "$1" = "wifi" ]; then
  kitty -e nmtui
elif [ "$1" = "audio" ]; then
  pavucontrol
elif [ "$1" = "calendar" ]; then
  calendar
fi
